### ISSUE TITLE
Page up changes window layout

### ISSUE THREAD

**Issue by msperl** [ubergrape/grape-electron#73]
On windows pressing "page up" while in the "Enter a message..." field produces the layout to change.

The window now looks like this:
![grafik](https://user-images.githubusercontent.com/2638784/62538627-8f733800-b853-11e9-81c4-428bbde05256.png)

The groups, favourites, are no longer visible (only the rightmost part) and there is a white area to the right that is of the width that is missing on the left side.

Closing the window does not help - when reopened it opens with the same issue.

Only solution: restart of the application

**Comment by AleshaOleg** [comment]
hey @msperl, seems it fixed now! please check it out

**Comment by msperl** [comment]
I have to tell you that with version 3.0.1 the issue still is reproducible...
just type into the chat window (without a return) and press "Page-Up"
